# Generated by Django 5.1.3 on 2024-12-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
    ]
